<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menu_items')->insert(
            [
                ['position' => 1, 'name' => 'Picanha (Porção pequena)', 'price' => 33.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 2, 'name' => 'Picanha (Porção Grande)', 'price' => 38.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 6, 'name' => 'Peito de Frango', 'price' => 30.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 1, 'name' => 'Picanha a Palito ', 'price' => 28.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 3, 'name' => 'Coxinha de Frango', 'price' => 4.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 1, 'name' => 'Coca Cola', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 2, 'name' => 'Coca Cola Zero', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 1, 'name' => 'Super Bock', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 2, 'name' => 'Sagres', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 3, 'name' => 'Carne Seca (Porção pequena)', 'price' => 30.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 4, 'name' => 'Carne Seca (Porção Grande)', 'price' => 35.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 1, 'name' => 'Mousse de maracujá', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 5, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 2, 'name' => 'Pudim', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 5, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 3, 'name' => 'Bolo', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 5, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 7, 'name' => 'Fígado acebolado', 'price' => 25.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 5, 'name' => 'Bisteca', 'price' => 44.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 8, 'name' => 'Filé de Peixe', 'price' => 30.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 9, 'name' => 'Camarão', 'price' => 38.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 10, 'name' => 'Bacalhau', 'price' => 30.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 2, 'name' => 'Carne-seca á palito', 'price' => 28.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 4, 'name' => 'Pastel de Queijo', 'price' => 10.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 5, 'name' => 'Pastel de Frango', 'price' => 10.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 6, 'name' => 'Pastel de Carne', 'price' => 10.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 7, 'name' => 'Pastel Misturado', 'price' => 10.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 8, 'name' => 'Caldo de costela e mandioca', 'price' => 17.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 9, 'name' => 'Caldo de milho com camarão', 'price' => 17.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 10, 'name' => 'Batata ou mandioca frita (Porção Pequena)', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 11, 'name' => 'Batata ou mandioca frita (Porção Grande)', 'price' => 14.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 12, 'name' => 'Banana Frita', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 13, 'name' => 'Salada Simples', 'price' => 6.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 14, 'name' => 'Salada da casa ', 'price' => 21.00, 'image_path' => NULL, 'menu_section_id' => 1, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 11, 'name' => 'Feijoada', 'price' => 33.00, 'image_path' => NULL, 'menu_section_id' => 2, 'printer_id' => 2, 'created_at' => now()],
                ['position' => 3, 'name' => 'Ice Tea', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 4, 'name' => 'Fanta Laranja', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 5, 'name' => 'Fanta Uva', 'price' => 7.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 6, 'name' => 'Sprite', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 7, 'name' => 'Arkina', 'price' => 4.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 8, 'name' => 'Rähzünser', 'price' => 4.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 9, 'name' => 'Guarana', 'price' => 7.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 3, 'name' => 'Feldschlösschen', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 4, 'name' => 'Skol', 'price' => 7.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 5, 'name' => 'Brahma', 'price' => 7.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 6, 'name' => 'Heineken', 'price' => 5.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 7, 'name' => 'Capirinha', 'price' => 17.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 8, 'name' => 'Aperol', 'price' => 17.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 9, 'name' => 'Piña colada', 'price' => 17.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 10, 'name' => 'Senza Parole Primitivo', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 11, 'name' => 'Senza Parole Negro Amaro', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 12, 'name' => 'Real Talento tinto', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 13, 'name' => 'Lideranca tinto', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 14, 'name' => 'Senza Parole Bianco', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 4, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 10, 'name' => 'Suco', 'price' => 8.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 12, 'name' => 'Frischgepresste Säfte', 'price' => 7.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
                ['position' => 11, 'name' => 'Sucos (com leite)', 'price' => 10.00, 'image_path' => NULL, 'menu_section_id' => 3, 'printer_id' => 1, 'created_at' => now()],
            ]
        );

        DB::table('menu_selectable_sides')->insert([
            ['menu_side_id' => 3, 'menu_item_id' => 1, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 1, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 2, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 2, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 3, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 3, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 10, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 10, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 11, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 11, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 16, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 16, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 17, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 17, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 18, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 18, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 19, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 19, 'created_at' => now()],
            ['menu_side_id' => 3, 'menu_item_id' => 32, 'created_at' => now()],
            ['menu_side_id' => 4, 'menu_item_id' => 32, 'created_at' => now()],
            ['menu_side_id' => 6, 'menu_item_id' => 32, 'created_at' => now()],
            ['menu_side_id' => 7, 'menu_item_id' => 32, 'created_at' => now()],
            ['menu_side_id' => 8, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 9, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 10, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 11, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 12, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 13, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 14, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 15, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 16, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 17, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 18, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 19, 'menu_item_id' => 52, 'created_at' => now()],
            ['menu_side_id' => 20, 'menu_item_id' => 53, 'created_at' => now()],
            ['menu_side_id' => 21, 'menu_item_id' => 53, 'created_at' => now()],
            ['menu_side_id' => 8, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 9, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 10, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 11, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 12, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 13, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 14, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 15, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 16, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 17, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 18, 'menu_item_id' => 54, 'created_at' => now()],
            ['menu_side_id' => 19, 'menu_item_id' => 54, 'created_at' => now()],
        ]);

        DB::table('menu_fixed_sides')->insert(
            [
                ['menu_side_id' => 1, 'menu_item_id' => 1, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 1, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 2, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 2, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 10, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 10, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 11, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 11, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 15, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 15, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 16, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 16, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 17, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 17, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 18, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 18, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 19, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 19, 'created_at' => now()],
                ['menu_side_id' => 1, 'menu_item_id' => 32, 'created_at' => now()],
                ['menu_side_id' => 2, 'menu_item_id' => 32, 'created_at' => now()],
                ['menu_side_id' => 5, 'menu_item_id' => 32, 'created_at' => now()],
            ]
        );
    }
}
